# Apply this yaml to disable the Operator-Hub in an airgapped environment
apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  annotations:
    capability.openshift.io/name: marketplace
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    release.openshift.io/create-only: 'true'
  name: cluster
spec:
  sources:
    - disabled: true
      name: certified-operators
    - disabled: true
      name: redhat-operators
    - disabled: true
      name: community-operators
    - disabled: true
      name: redhat-marketplace
