# You need to apply the catalogsource with the image of your mirrored operators
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index
  namespace: openshift-marketplace
spec:
  image: patrick-local-docker-repo.artifactory.home.local/mirror/oc-mirror-metadata/redhat/redhat-operator-index:v4.14
  sourceType: grpc