# Create the Namespace
# oc create ns openshift-gitops-operator
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-gitops-operator
---
# Install Operatorgroup
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  upgradeStrategy: Default
---
# Install Operator/Subscription for Gitops
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
---